-- tadawul_companies_insert_statements.sql
-- Generated by scripts/discover_tadawul_companies.py — NOT executed against
-- Neon by this script.
-- Source: a list the project owner states they fetched live from
-- argaam.com/en on 2026-09-01, pasted into this session as raw text and
-- transcribed here — NOT independently fetched or verified by this script
-- (WebFetch was confirmed fully blocked in the authoring sandbox).
-- name_ar is NULL for every row — not available from this source.
-- Each INSERT is guarded by WHERE NOT EXISTS (core.companies has no real
-- UNIQUE/exclusion constraint on ticker to target with ON CONFLICT — verified
-- against schema.sql this session).
-- Review before running manually (e.g. via Neon SQL Editor / Render Shell).

-- 250 companies

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2222', NULL, 'SAUDI ARAMCO', 'Energy', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2222'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2030', NULL, 'SARCO', 'Energy', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2030'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2380', NULL, 'PETRO RABIGH', 'Energy', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2380'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4030', NULL, 'BAHRI', 'Energy', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4030'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2381', NULL, 'ARABIAN DRILLING', 'Energy', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2381'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2382', NULL, 'ADES', 'Energy', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2382'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1201', NULL, 'TAKWEEN', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1201'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1202', NULL, 'MEPCO', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1202'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1210', NULL, 'BCI', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1210'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1211', NULL, 'MAADEN', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1211'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1301', NULL, 'ASLAK', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1301'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1304', NULL, 'ALYAMAMAH STEEL', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1304'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1320', NULL, 'SSP', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1320'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2001', NULL, 'CHEMANOL', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2001'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2020', NULL, 'SABIC AGRI-NUTRIENTS', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2020'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2090', NULL, 'NGC', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2090'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2150', NULL, 'ZOUJAJ', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2150'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2170', NULL, 'ALUJAIN', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2170'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2180', NULL, 'FIPCO', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2180'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2200', NULL, 'APC', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2200'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2210', NULL, 'NAMA CHEMICALS', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2210'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2220', NULL, 'MAADANIYAH', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2220'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2240', NULL, 'SENAAT', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2240'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2250', NULL, 'SIIG', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2250'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2300', NULL, 'SPM', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2300'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2310', NULL, 'SIPCHEM', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2310'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2350', NULL, 'SAUDI KAYAN', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2350'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3002', NULL, 'NAJRAN CEMENT', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3002'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3003', NULL, 'CITY CEMENT', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3003'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3004', NULL, 'NORTHERN CEMENT', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3004'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3005', NULL, 'UACC', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3005'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3010', NULL, 'ACC', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3010'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3020', NULL, 'YC', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3020'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3030', NULL, 'SAUDI CEMENT', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3030'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3040', NULL, 'QACCO', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3040'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3050', NULL, 'SPCC', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3050'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3060', NULL, 'YCC', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3060'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3080', NULL, 'EPCCO', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3080'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3090', NULL, 'TCC', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3090'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3091', NULL, 'JOUF CEMENT', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3091'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3092', NULL, 'RIYADH CEMENT', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3092'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2060', NULL, 'TASNEE', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2060'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3008', NULL, 'ALKATHIRI', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3008'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3007', NULL, 'OASIS', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3007'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1321', NULL, 'EAST PIPES', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1321'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1322', NULL, 'AMAK', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1322'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2223', NULL, 'LUBEREF', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2223'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1324', NULL, 'SALEH ALRASHED', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1324'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2360', NULL, 'SVCP', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2360'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1323', NULL, 'UCIC', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1323'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4143', NULL, 'TALCO', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4143'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1212', NULL, 'ASTRA INDUSTRIAL', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1212'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4146', NULL, 'GAS', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4146'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1302', NULL, 'BAWAN', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1302'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1303', NULL, 'EIC', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1303'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4148', NULL, 'ALWASAIL INDUSTRIAL', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4148'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4145', NULL, 'OGC', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4145'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2040', NULL, 'SAUDI CERAMICS', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2040'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2110', NULL, 'SAUDI CABLE', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2110'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4144', NULL, 'RAOOM', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4144'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2160', NULL, 'AMIANTIT', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2160'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2320', NULL, 'ALBABTAIN', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2320'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2370', NULL, 'MESC', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2370'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4140', NULL, 'SIECO', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4140'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4141', NULL, 'ALOMRAN', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4141'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4142', NULL, 'RIYADH CABLES', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4142'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1214', NULL, 'SHAKER', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1214'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4110', NULL, 'BATIC', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4110'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4147', NULL, 'CGS', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4147'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4270', NULL, 'SPPC', 'Commercial & Professional Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4270'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6004', NULL, 'CATRION', 'Commercial & Professional Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6004'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1832', NULL, 'SADR', 'Commercial & Professional Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1832'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1831', NULL, 'MAHARAH', 'Commercial & Professional Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1831'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1833', NULL, 'ALMAWARID', 'Commercial & Professional Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1833'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1834', NULL, 'SMASCO', 'Commercial & Professional Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1834'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1835', NULL, 'TAMKEEN', 'Commercial & Professional Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1835'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4031', NULL, 'SGS', 'Transportation', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4031'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4040', NULL, 'SAPTCO', 'Transportation', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4040'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4260', NULL, 'BUDGET SAUDI', 'Transportation', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4260'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2190', NULL, 'SISCO HOLDING', 'Transportation', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2190'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4261', NULL, 'THEEB', 'Transportation', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4261'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4263', NULL, 'SAL', 'Transportation', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4263'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4262', NULL, 'LUMI', 'Transportation', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4262'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4265', NULL, 'CHERRY', 'Transportation', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4265'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4264', NULL, 'FLYNAS', 'Transportation', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4264'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1213', NULL, 'NASEEJ', 'Consumer Durables & Apparel', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1213'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2130', NULL, 'SIDC', 'Consumer Durables & Apparel', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2130'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2340', NULL, 'ARTEX', 'Consumer Durables & Apparel', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2340'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4011', NULL, 'LAZURDE', 'Consumer Durables & Apparel', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4011'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4180', NULL, 'FITAIHI GROUP', 'Consumer Durables & Apparel', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4180'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4012', NULL, 'ALASEEL', 'Consumer Durables & Apparel', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4012'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1810', NULL, 'SEERA', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1810'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6013', NULL, 'DWF', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6013'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1820', NULL, 'BAAN', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1820'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4170', NULL, 'TECO', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4170'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4290', NULL, 'ALKHALEEJ TRNG', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4290'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6017', NULL, 'JAHEZ', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6017'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6002', NULL, 'HERFY FOODS', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6002'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1830', NULL, 'LEEJAM SPORTS', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1830'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6012', NULL, 'RAYDAN', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6012'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4291', NULL, 'NCLE', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4291'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4292', NULL, 'ATAA', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4292'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6014', NULL, 'ALAMAR', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6014'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6015', NULL, 'AMERICANA', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6015'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6016', NULL, 'BURGERIZZR', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6016'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6018', NULL, 'SPORT CLUBS', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6018'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6019', NULL, 'ALMASAR ALSHAMIL', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6019'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6022', NULL, 'ARMAH', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6022'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4070', NULL, 'TAPRCO', 'Media and Entertainment', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4070'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4210', NULL, 'SRMG', 'Media and Entertainment', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4210'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4071', NULL, 'ALARABIA', 'Media and Entertainment', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4071'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4072', NULL, 'MBC GROUP', 'Media and Entertainment', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4072'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4003', NULL, 'EXTRA', 'Consumer Discretionary Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4003'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4008', NULL, 'SACO', 'Consumer Discretionary Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4008'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4050', NULL, 'SASCO', 'Consumer Discretionary Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4050'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4190', NULL, 'JARIR', 'Consumer Discretionary Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4190'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4240', NULL, 'CENOMI RETAIL', 'Consumer Discretionary Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4240'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4191', NULL, 'ABO MOATI', 'Consumer Discretionary Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4191'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4051', NULL, 'BAAZEEM', 'Consumer Discretionary Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4051'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4192', NULL, 'ALSAIF GALLERY', 'Consumer Discretionary Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4192'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4193', NULL, 'NICE ONE', 'Consumer Discretionary Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4193'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4194', NULL, 'BUILD STATION', 'Consumer Discretionary Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4194'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4200', NULL, 'ALDREES', 'Consumer Discretionary Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4200'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4001', NULL, 'A.OTHAIM MARKET', 'Consumer Staples Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4001'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4006', NULL, 'FARM SUPERSTORES', 'Consumer Staples Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4006'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4061', NULL, 'ANAAM HOLDING', 'Consumer Staples Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4061'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4160', NULL, 'THIMAR', 'Consumer Staples Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4160'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4161', NULL, 'BINDAWOOD', 'Consumer Staples Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4161'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4162', NULL, 'ALMUNAJEM', 'Consumer Staples Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4162'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4164', NULL, 'NAHDI', 'Consumer Staples Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4164'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4163', NULL, 'ALDAWAA', 'Consumer Staples Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4163'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2050', NULL, 'SAVOLA GROUP', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2050'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2100', NULL, 'WAFRAH', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2100'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2270', NULL, 'SADAFCO', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2270'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2280', NULL, 'ALMARAI', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2280'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6001', NULL, 'HB', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6001'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2288', NULL, 'NOFOTH', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2288'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6010', NULL, 'NADEC', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6010'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6020', NULL, 'GACO', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6020'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6040', NULL, 'TADCO', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6040'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6050', NULL, 'SFICO', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6050'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6060', NULL, 'SHARQIYAH DEV', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6060'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6070', NULL, 'ALJOUF', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6070'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6090', NULL, 'JAZADCO', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6090'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2281', NULL, 'TANMIAH', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2281'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2282', NULL, 'NAQI', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2282'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2283', NULL, 'FIRST MILLS', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2283'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4080', NULL, 'SINAD HOLDING', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4080'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2284', NULL, 'MODERN MILLS', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2284'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2285', NULL, 'ARABIAN MILLS', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2285'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2286', NULL, 'FOURTH MILLING', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2286'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2287', NULL, 'ENTAJ', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2287'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4002', NULL, 'MOUWASAT', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4002'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4021', NULL, 'CMCER', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4021'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4004', NULL, 'DALLAH HEALTH', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4004'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4005', NULL, 'CARE', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4005'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4007', NULL, 'ALHAMMADI', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4007'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4009', NULL, 'SAUDI GERMAN HEALTH', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4009'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2230', NULL, 'CHEMICAL', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2230'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4013', NULL, 'SULAIMAN ALHABIB', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4013'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2140', NULL, 'AYYAN', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2140'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4014', NULL, 'EQUIPMENT HOUSE', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4014'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4017', NULL, 'FAKEEH CARE', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4017'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4018', NULL, 'ALMOOSA', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4018'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4019', NULL, 'SMC HEALTHCARE', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4019'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2070', NULL, 'SPIMACO', 'Pharma, Biotech & Life Sciences', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2070'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4015', NULL, 'JAMJOOM PHARMA', 'Pharma, Biotech & Life Sciences', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4015'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4016', NULL, 'AVALON PHARMA', 'Pharma, Biotech & Life Sciences', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4016'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1010', NULL, 'RIBL', 'Banks', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1010'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1020', NULL, 'BJAZ', 'Banks', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1020'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1030', NULL, 'SAIB', 'Banks', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1030'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1050', NULL, 'BSF', 'Banks', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1050'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1060', NULL, 'SAB', 'Banks', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1060'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1080', NULL, 'ANB', 'Banks', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1080'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1120', NULL, 'ALRAJHI', 'Banks', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1120'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1140', NULL, 'ALBILAD', 'Banks', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1140'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1150', NULL, 'ALINMA', 'Banks', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1150'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1180', NULL, 'SNB', 'Banks', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1180'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2120', NULL, 'SAIC', 'Financial Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2120'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4280', NULL, 'KINGDOM', 'Financial Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4280'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4130', NULL, 'SAUDI DARB', 'Financial Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4130'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4081', NULL, 'NAYIFAT', 'Financial Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4081'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1111', NULL, 'TADAWUL GROUP', 'Financial Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1111'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4082', NULL, 'MRNA', 'Financial Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4082'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1182', NULL, 'AMLAK', 'Financial Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1182'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1183', NULL, 'SHL', 'Financial Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1183'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4083', NULL, 'TASHEEL', 'Financial Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4083'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4084', NULL, 'DERAYAH', 'Financial Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4084'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8010', NULL, 'TAWUNIYA', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8010'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8012', NULL, 'JAZIRA TAKAFUL', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8012'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8020', NULL, 'MALATH INSURANCE', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8020'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8030', NULL, 'MEDGULF', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8030'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8040', NULL, 'MUTAKAMELA', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8040'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8050', NULL, 'SALAMA', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8050'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8060', NULL, 'WALAA', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8060'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8070', NULL, 'ARABIAN SHIELD', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8070'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8190', NULL, 'UCA', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8190'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8230', NULL, 'ALRAJHI TAKAFUL', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8230'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8280', NULL, 'LIVA', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8280'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8150', NULL, 'ACIG', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8150'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8210', NULL, 'BUPA ARABIA', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8210'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8180', NULL, 'ALSAGR INSURANCE', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8180'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8170', NULL, 'ALETIHAD', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8170'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8100', NULL, 'SAICO', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8100'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8120', NULL, 'GULF UNION ALAHLIA', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8120'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8200', NULL, 'SAUDI RE', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8200'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8160', NULL, 'AICC', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8160'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8250', NULL, 'GIG', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8250'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8240', NULL, 'CHUBB', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8240'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8260', NULL, 'GULF GENERAL', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8260'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8300', NULL, 'WATANIYA', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8300'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8310', NULL, 'AMANA INSURANCE', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8310'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8311', NULL, 'ENAYA', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8311'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8313', NULL, 'RASAN', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8313'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '7010', NULL, 'STC', 'Telecommunication Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '7010'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '7020', NULL, 'ETIHAD ETISALAT', 'Telecommunication Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '7020'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '7030', NULL, 'ZAIN KSA', 'Telecommunication Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '7030'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '7040', NULL, 'GO TELECOM', 'Telecommunication Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '7040'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2080', NULL, 'GASCO HOLDING', 'Utilities', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2080'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '5110', NULL, 'SAUDI ENERGY', 'Utilities', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '5110'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2081', NULL, 'AWPT', 'Utilities', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2081'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2082', NULL, 'ACWA', 'Utilities', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2082'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2083', NULL, 'MARAFIQ', 'Utilities', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2083'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2084', NULL, 'MIAHONA', 'Utilities', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2084'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4020', NULL, 'ALAKARIA', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4020'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4324', NULL, 'BANAN', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4324'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4328', NULL, 'LADUN', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4328'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4323', NULL, 'SUMOU', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4323'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4090', NULL, 'TAIBA', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4090'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4100', NULL, 'MCDC', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4100'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4150', NULL, 'ARDCO', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4150'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4220', NULL, 'EMAAR EC', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4220'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4230', NULL, 'RED SEA', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4230'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4250', NULL, 'JABAL OMAR', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4250'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4300', NULL, 'DAR ALARKAN', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4300'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4310', NULL, 'KEC', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4310'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4320', NULL, 'ALANDALUS', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4320'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4321', NULL, 'CENOMI CENTERS', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4321'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4322', NULL, 'RETAL', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4322'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4326', NULL, 'ALMAJDIAH', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4326'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4325', NULL, 'MASAR', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4325'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4327', NULL, 'AlRAMZ', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4327'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '7201', NULL, 'ARAB SEA', 'Software & Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '7201'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '7211', NULL, 'AZM', 'Software & Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '7211'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '7200', NULL, 'MIS', 'Software & Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '7200'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '7202', NULL, 'SOLUTIONS', 'Software & Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '7202'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '7203', NULL, 'ELM', 'Software & Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '7203'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '7204', NULL, '2P', 'Software & Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '7204'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '7205', NULL, 'DBS', 'Software & Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '7205'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4165', NULL, 'ALMAJED OUD', 'Household & Personal Products', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4165'
);
