-- tadawul_companies_insert_statements.sql
-- Generated by scripts/discover_tadawul_companies.py — NOT executed against
-- Neon by this script.
-- Source: two lists (English: argaam.com/en; Arabic:
-- argaam.com/ar/company/companylist) the project owner states they
-- fetched live themselves and pasted into this session as raw text,
-- matched ticker-by-ticker — NOT independently fetched or verified by
-- this script (WebFetch was confirmed fully blocked in the authoring
-- sandbox). Every row below has both name_en and name_ar populated
-- (core.companies.name_ar is NOT NULL); a ticker with no Arabic-name
-- match was excluded, not given an empty/placeholder value — see the
-- script's own console output for which tickers, if any, were excluded.
-- Each INSERT is guarded by WHERE NOT EXISTS (core.companies has no real
-- UNIQUE/exclusion constraint on ticker to target with ON CONFLICT — verified
-- against schema.sql this session).
-- Review before running manually (e.g. via Neon SQL Editor / Render Shell).

-- 250 companies

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2222', 'أرامكو السعودية', 'SAUDI ARAMCO', 'Energy', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2222'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2030', 'المصافي', 'SARCO', 'Energy', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2030'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2380', 'بترو رابغ', 'PETRO RABIGH', 'Energy', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2380'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4030', 'البحري', 'BAHRI', 'Energy', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4030'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2381', 'الحفر العربية', 'ARABIAN DRILLING', 'Energy', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2381'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2382', 'أديس', 'ADES', 'Energy', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2382'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1201', 'تكوين', 'TAKWEEN', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1201'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1202', 'مبكو', 'MEPCO', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1202'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1210', 'بي سي آي', 'BCI', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1210'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1211', 'معادن', 'MAADEN', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1211'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1301', 'أسلاك', 'ASLAK', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1301'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1304', 'اليمامة للحديد', 'ALYAMAMAH STEEL', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1304'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1320', 'أنابيب السعودية', 'SSP', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1320'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2001', 'كيمانول', 'CHEMANOL', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2001'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2020', 'سابك للمغذيات الزراعية', 'SABIC AGRI-NUTRIENTS', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2020'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2090', 'جبسكو', 'NGC', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2090'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2150', 'زجاج', 'ZOUJAJ', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2150'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2170', 'اللجين', 'ALUJAIN', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2170'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2180', 'فيبكو', 'FIPCO', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2180'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2200', 'أنابيب', 'APC', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2200'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2210', 'نماء للكيماويات', 'NAMA CHEMICALS', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2210'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2220', 'معدنية', 'MAADANIYAH', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2220'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2240', 'صناعات', 'SENAAT', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2240'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2250', 'المجموعة السعودية', 'SIIG', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2250'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2300', 'صناعة الورق', 'SPM', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2300'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2310', 'سبكيم العالمية', 'SIPCHEM', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2310'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2350', 'كيان السعودية', 'SAUDI KAYAN', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2350'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3002', 'أسمنت نجران', 'NAJRAN CEMENT', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3002'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3003', 'أسمنت المدينة', 'CITY CEMENT', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3003'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3004', 'أسمنت الشمالية', 'NORTHERN CEMENT', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3004'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3005', 'أسمنت ام القرى', 'UACC', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3005'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3010', 'أسمنت العربية', 'ACC', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3010'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3020', 'أسمنت اليمامة', 'YC', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3020'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3030', 'أسمنت السعودية', 'SAUDI CEMENT', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3030'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3040', 'أسمنت القصيم', 'QACCO', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3040'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3050', 'أسمنت الجنوب', 'SPCC', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3050'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3060', 'أسمنت ينبع', 'YCC', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3060'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3080', 'أسمنت الشرقية', 'EPCCO', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3080'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3090', 'أسمنت تبوك', 'TCC', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3090'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3091', 'أسمنت الجوف', 'JOUF CEMENT', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3091'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3092', 'أسمنت الرياض', 'RIYADH CEMENT', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3092'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2060', 'التصنيع', 'TASNEE', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2060'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3008', 'الكثيري', 'ALKATHIRI', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3008'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '3007', 'الواحة', 'OASIS', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '3007'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1321', 'أنابيب الشرق', 'EAST PIPES', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1321'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1322', 'أماك', 'AMAK', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1322'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2223', 'لوبريف', 'LUBEREF', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2223'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1324', 'صالح الراشد', 'SALEH ALRASHED', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1324'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2360', 'الفخارية', 'SVCP', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2360'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1323', 'يو سي آي سي', 'UCIC', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1323'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4143', 'تالكو', 'TALCO', 'Materials', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4143'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1212', 'أسترا الصناعية', 'ASTRA INDUSTRIAL', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1212'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4146', 'جاز', 'GAS', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4146'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1302', 'بوان', 'BAWAN', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1302'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1303', 'الصناعات الكهربائية', 'EIC', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1303'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4148', 'الوسائل الصناعية', 'ALWASAIL INDUSTRIAL', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4148'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4145', 'أو جي سي', 'OGC', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4145'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2040', 'الخزف السعودي', 'SAUDI CERAMICS', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2040'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2110', 'الكابلات السعودية', 'SAUDI CABLE', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2110'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4144', 'رؤوم', 'RAOOM', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4144'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2160', 'أميانتيت', 'AMIANTIT', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2160'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2320', 'البابطين', 'ALBABTAIN', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2320'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2370', 'مسك', 'MESC', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2370'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4140', 'صادرات', 'SIECO', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4140'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4141', 'العمران', 'ALOMRAN', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4141'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4142', 'كابلات الرياض', 'RIYADH CABLES', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4142'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1214', 'شاكر', 'SHAKER', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1214'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4110', 'باتك', 'BATIC', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4110'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4147', 'سي جي إس', 'CGS', 'Capital Goods', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4147'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4270', 'طباعة وتغليف', 'SPPC', 'Commercial & Professional Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4270'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6004', 'كاتريون', 'CATRION', 'Commercial & Professional Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6004'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1832', 'صدر', 'SADR', 'Commercial & Professional Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1832'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1831', 'مهارة', 'MAHARAH', 'Commercial & Professional Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1831'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1833', 'الموارد', 'ALMAWARID', 'Commercial & Professional Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1833'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1834', 'سماسكو', 'SMASCO', 'Commercial & Professional Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1834'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1835', 'تمكين', 'TAMKEEN', 'Commercial & Professional Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1835'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4031', 'الخدمات الأرضية', 'SGS', 'Transportation', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4031'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4040', 'سابتكو', 'SAPTCO', 'Transportation', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4040'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4260', 'بدجت السعودية', 'BUDGET SAUDI', 'Transportation', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4260'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2190', 'سيسكو القابضة', 'SISCO HOLDING', 'Transportation', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2190'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4261', 'ذيب', 'THEEB', 'Transportation', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4261'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4263', 'سال', 'SAL', 'Transportation', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4263'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4262', 'لومي', 'LUMI', 'Transportation', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4262'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4265', 'شري', 'CHERRY', 'Transportation', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4265'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4264', 'طيران ناس', 'FLYNAS', 'Transportation', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4264'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1213', 'نسيج', 'NASEEJ', 'Consumer Durables & Apparel', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1213'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2130', 'صدق', 'SIDC', 'Consumer Durables & Apparel', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2130'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2340', 'ارتيكس', 'ARTEX', 'Consumer Durables & Apparel', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2340'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4011', 'لازوردي', 'LAZURDE', 'Consumer Durables & Apparel', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4011'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4180', 'مجموعة فتيحي', 'FITAIHI GROUP', 'Consumer Durables & Apparel', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4180'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4012', 'الأصيل', 'ALASEEL', 'Consumer Durables & Apparel', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4012'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1810', 'سيرا', 'SEERA', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1810'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6013', 'التطويرية الغذائية', 'DWF', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6013'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1820', 'بان', 'BAAN', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1820'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4170', 'شمس', 'TECO', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4170'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4290', 'الخليج للتدريب', 'ALKHALEEJ TRNG', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4290'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6017', 'جاهز', 'JAHEZ', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6017'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6002', 'هرفي للأغذية', 'HERFY FOODS', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6002'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1830', 'لجام للرياضة', 'LEEJAM SPORTS', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1830'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6012', 'ريدان', 'RAYDAN', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6012'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4291', 'الوطنية للتعليم', 'NCLE', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4291'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4292', 'عطاء', 'ATAA', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4292'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6014', 'الآمار', 'ALAMAR', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6014'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6015', 'أمريكانا', 'AMERICANA', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6015'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6016', 'برغرايززر', 'BURGERIZZR', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6016'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6018', 'الأندية للرياضة', 'SPORT CLUBS', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6018'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6019', 'المسار الشامل', 'ALMASAR ALSHAMIL', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6019'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6022', 'أرماح', 'ARMAH', 'Consumer Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6022'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4070', 'تهامة', 'TAPRCO', 'Media and Entertainment', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4070'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4210', 'الأبحاث والإعلام', 'SRMG', 'Media and Entertainment', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4210'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4071', 'العربية', 'ALARABIA', 'Media and Entertainment', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4071'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4072', 'مجموعة إم بي سي', 'MBC GROUP', 'Media and Entertainment', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4072'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4003', 'إكسترا', 'EXTRA', 'Consumer Discretionary Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4003'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4008', 'ساكو', 'SACO', 'Consumer Discretionary Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4008'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4050', 'ساسكو', 'SASCO', 'Consumer Discretionary Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4050'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4190', 'جرير', 'JARIR', 'Consumer Discretionary Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4190'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4240', 'سينومي ريتيل', 'CENOMI RETAIL', 'Consumer Discretionary Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4240'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4191', 'أبو معطي', 'ABO MOATI', 'Consumer Discretionary Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4191'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4051', 'باعظيم', 'BAAZEEM', 'Consumer Discretionary Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4051'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4192', 'السيف غاليري', 'ALSAIF GALLERY', 'Consumer Discretionary Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4192'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4193', 'نايس ون', 'NICE ONE', 'Consumer Discretionary Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4193'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4194', 'محطة البناء', 'BUILD STATION', 'Consumer Discretionary Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4194'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4200', 'الدريس', 'ALDREES', 'Consumer Discretionary Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4200'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4001', 'أسواق ع العثيم', 'A.OTHAIM MARKET', 'Consumer Staples Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4001'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4006', 'أسواق المزرعة', 'FARM SUPERSTORES', 'Consumer Staples Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4006'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4061', 'أنعام القابضة', 'ANAAM HOLDING', 'Consumer Staples Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4061'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4160', 'ثمار', 'THIMAR', 'Consumer Staples Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4160'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4161', 'بن داود', 'BINDAWOOD', 'Consumer Staples Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4161'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4162', 'المنجم', 'ALMUNAJEM', 'Consumer Staples Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4162'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4164', 'النهدي', 'NAHDI', 'Consumer Staples Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4164'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4163', 'الدواء', 'ALDAWAA', 'Consumer Staples Distribution & Retail', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4163'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2050', 'مجموعة صافولا', 'SAVOLA GROUP', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2050'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2100', 'وفرة', 'WAFRAH', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2100'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2270', 'سدافكو', 'SADAFCO', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2270'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2280', 'المراعي', 'ALMARAI', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2280'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6001', 'حلواني إخوان', 'HB', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6001'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2288', 'نفوذ', 'NOFOTH', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2288'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6010', 'نادك', 'NADEC', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6010'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6020', 'جاكو', 'GACO', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6020'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6040', 'تبوك الزراعية', 'TADCO', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6040'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6050', 'الأسماك', 'SFICO', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6050'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6060', 'الشرقية للتنمية', 'SHARQIYAH DEV', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6060'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6070', 'الجوف', 'ALJOUF', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6070'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '6090', 'جازادكو', 'JAZADCO', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '6090'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2281', 'تنمية', 'TANMIAH', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2281'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2282', 'نقي', 'NAQI', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2282'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2283', 'المطاحن الأولى', 'FIRST MILLS', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2283'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4080', 'سناد القابضة', 'SINAD HOLDING', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4080'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2284', 'المطاحن الحديثة', 'MODERN MILLS', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2284'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2285', 'المطاحن العربية', 'ARABIAN MILLS', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2285'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2286', 'المطاحن الرابعة', 'FOURTH MILLING', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2286'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2287', 'إنتاج', 'ENTAJ', 'Food & Beverages', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2287'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4002', 'المواساة', 'MOUWASAT', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4002'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4021', 'المركز الكندي الطبي', 'CMCER', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4021'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4004', 'دله الصحية', 'DALLAH HEALTH', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4004'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4005', 'رعاية', 'CARE', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4005'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4007', 'الحمادي', 'ALHAMMADI', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4007'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4009', 'السعودي الألماني الصحية', 'SAUDI GERMAN HEALTH', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4009'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2230', 'الكيميائية', 'CHEMICAL', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2230'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4013', 'سليمان الحبيب', 'SULAIMAN ALHABIB', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4013'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2140', 'أيان', 'AYYAN', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2140'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4014', 'دار المعدات', 'EQUIPMENT HOUSE', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4014'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4017', 'فقيه الطبية', 'FAKEEH CARE', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4017'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4018', 'الموسى', 'ALMOOSA', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4018'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4019', 'اس ام سي للرعاية الصحية', 'SMC HEALTHCARE', 'Health Care Equipment & Svc', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4019'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2070', 'الدوائية', 'SPIMACO', 'Pharma, Biotech & Life Sciences', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2070'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4015', 'جمجوم فارما', 'JAMJOOM PHARMA', 'Pharma, Biotech & Life Sciences', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4015'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4016', 'أفالون فارما', 'AVALON PHARMA', 'Pharma, Biotech & Life Sciences', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4016'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1010', 'الرياض', 'RIBL', 'Banks', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1010'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1020', 'الجزيرة', 'BJAZ', 'Banks', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1020'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1030', 'الإستثمار', 'SAIB', 'Banks', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1030'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1050', 'بي اس اف', 'BSF', 'Banks', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1050'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1060', 'الأول', 'SAB', 'Banks', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1060'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1080', 'العربي', 'ANB', 'Banks', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1080'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1120', 'الراجحي', 'ALRAJHI', 'Banks', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1120'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1140', 'البلاد', 'ALBILAD', 'Banks', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1140'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1150', 'الإنماء', 'ALINMA', 'Banks', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1150'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1180', 'الأهلي', 'SNB', 'Banks', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1180'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2120', 'متطورة', 'SAIC', 'Financial Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2120'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4280', 'المملكة', 'KINGDOM', 'Financial Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4280'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4130', 'درب السعودية', 'SAUDI DARB', 'Financial Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4130'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4081', 'النايفات', 'NAYIFAT', 'Financial Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4081'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1111', 'مجموعة تداول', 'TADAWUL GROUP', 'Financial Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1111'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4082', 'مرنة', 'MRNA', 'Financial Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4082'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1182', 'أملاك', 'AMLAK', 'Financial Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1182'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '1183', 'سهل', 'SHL', 'Financial Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '1183'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4083', 'تسهيل', 'TASHEEL', 'Financial Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4083'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4084', 'دراية', 'DERAYAH', 'Financial Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4084'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8010', 'التعاونية', 'TAWUNIYA', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8010'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8012', 'جزيرة تكافل', 'JAZIRA TAKAFUL', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8012'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8020', 'ملاذ للتأمين', 'MALATH INSURANCE', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8020'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8030', 'ميدغلف للتأمين', 'MEDGULF', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8030'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8040', 'متكاملة', 'MUTAKAMELA', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8040'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8050', 'سلامة', 'SALAMA', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8050'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8060', 'ولاء', 'WALAA', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8060'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8070', 'الدرع العربي', 'ARABIAN SHIELD', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8070'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8190', 'المتحدة للتأمين', 'UCA', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8190'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8230', 'تكافل الراجحي', 'ALRAJHI TAKAFUL', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8230'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8280', 'ليفا', 'LIVA', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8280'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8150', 'أسيج', 'ACIG', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8150'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8210', 'بوبا العربية', 'BUPA ARABIA', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8210'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8180', 'الصقر للتأمين', 'ALSAGR INSURANCE', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8180'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8170', 'الاتحاد', 'ALETIHAD', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8170'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8100', 'سايكو', 'SAICO', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8100'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8120', 'إتحاد الخليج الأهلية', 'GULF UNION ALAHLIA', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8120'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8200', 'الإعادة السعودية', 'SAUDI RE', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8200'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8160', 'التأمين العربية', 'AICC', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8160'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8250', 'جي آي جي', 'GIG', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8250'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8240', 'تْشب', 'CHUBB', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8240'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8260', 'الخليجية العامة', 'GULF GENERAL', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8260'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8300', 'الوطنية', 'WATANIYA', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8300'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8310', 'أمانة للتأمين', 'AMANA INSURANCE', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8310'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8311', 'عناية', 'ENAYA', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8311'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '8313', 'رسن', 'RASAN', 'Insurance', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '8313'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '7010', 'اس تي سي', 'STC', 'Telecommunication Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '7010'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '7020', 'إتحاد إتصالات', 'ETIHAD ETISALAT', 'Telecommunication Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '7020'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '7030', 'زين السعودية', 'ZAIN KSA', 'Telecommunication Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '7030'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '7040', 'قو للإتصالات', 'GO TELECOM', 'Telecommunication Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '7040'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2080', 'الغاز القابضة', 'GASCO HOLDING', 'Utilities', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2080'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '5110', 'السعودية للطاقة', 'SAUDI ENERGY', 'Utilities', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '5110'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2081', 'الخريف', 'AWPT', 'Utilities', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2081'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2082', 'أكوا', 'ACWA', 'Utilities', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2082'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2083', 'مرافق', 'MARAFIQ', 'Utilities', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2083'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '2084', 'مياهنا', 'MIAHONA', 'Utilities', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '2084'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4020', 'العقارية', 'ALAKARIA', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4020'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4324', 'بنان', 'BANAN', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4324'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4328', 'لدن', 'LADUN', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4328'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4323', 'سمو', 'SUMOU', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4323'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4090', 'طيبة', 'TAIBA', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4090'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4100', 'مكة', 'MCDC', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4100'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4150', 'التعمير', 'ARDCO', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4150'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4220', 'إعمار', 'EMAAR EC', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4220'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4230', 'البحر الأحمر', 'RED SEA', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4230'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4250', 'جبل عمر', 'JABAL OMAR', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4250'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4300', 'دار الأركان', 'DAR ALARKAN', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4300'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4310', 'مدينة المعرفة', 'KEC', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4310'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4320', 'الأندلس', 'ALANDALUS', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4320'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4321', 'سينومي سنترز', 'CENOMI CENTERS', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4321'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4322', 'رتال', 'RETAL', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4322'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4326', 'الماجدية', 'ALMAJDIAH', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4326'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4325', 'مسار', 'MASAR', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4325'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4327', 'الرمز', 'AlRAMZ', 'Real Estate Mgmt & Dev''t', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4327'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '7201', 'بحر العرب', 'ARAB SEA', 'Software & Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '7201'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '7211', 'عزم', 'AZM', 'Software & Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '7211'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '7200', 'ام آي اس', 'MIS', 'Software & Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '7200'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '7202', 'سلوشنز', 'SOLUTIONS', 'Software & Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '7202'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '7203', 'علم', 'ELM', 'Software & Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '7203'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '7204', 'توبي', '2P', 'Software & Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '7204'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '7205', 'دي بي اس', 'DBS', 'Software & Services', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '7205'
);

INSERT INTO core.companies (company_id, ticker, name_ar, name_en, sector, status, created_at, updated_at)
SELECT gen_random_uuid(), '4165', 'الماجد للعود', 'ALMAJED OUD', 'Household & Personal Products', 'active', now(), now()
WHERE NOT EXISTS (
    SELECT 1 FROM core.companies WHERE ticker = '4165'
);
